export const vinylRecords = [
    {
        id: 1,
        title: 'Let There Be Rock',
        artist: 'AC/DC',
        year: 1990,
        style: 'Punk, Dub, Funk',
        country: 'USA',
        image: './img/1.jpg',
    },
    {
        id: 2,
        title: 'Back in Black',
        artist: 'AC/DC',
        year: 1980,
        style: 'Rock',
        country: 'USA',
        image: './img/2.jpg',
    },
	{
        id: 3,
        title: 'The Dark Side of the Moon',
        artist: 'Pink Floyd',
        year: 1973,
        style: 'Progressive Rock',
        country: 'UK',
        image: './img/3.jpg', 
    },
	{
        id: 4,
        title: 'Thriller',
        artist: 'Michael Jackson',
        year: 1982,
        style: 'Pop',
        country: 'USA',
        image: './img/4.jpg', 
    },
    {
        id: 5,
        title: 'Hotel California',
        artist: 'Eagles',
        year: 1976,
        style: 'Rock',
        country: 'USA',
        image: './img/5.jpg', 
    },
    {
        id: 6,
        title: 'Led Zeppelin IV',
        artist: 'Led Zeppelin',
        year: 1971,
        style: 'Rock',
        country: 'UK',
        image: './img/6.jpg', 
    },
    {
        id: 7,
        title: 'Rumours',
        artist: 'Fleetwood Mac',
        year: 1977,
        style: 'Rock',
        country: 'UK',
        image: './img/1.jpg', 
    },
    {
        id: 8,
        title: 'The Wall',
        artist: 'Pink Floyd',
        year: 1979,
        style: 'Progressive Rock',
        country: 'UK',
        image: './img/2.jpg', 
    },
    {
        id: 9,
        title: 'Abbey Road',
        artist: 'The Beatles',
        year: 1969,
        style: 'Rock',
        country: 'UK',
        image: './img/3.jpg', 
    },
    {
        id: 10,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/4.jpg', 
    },
    {
        id: 11,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/4.jpg', 
    },
    {
        id: 12,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/4.jpg', 
    },
    {
        id: 13,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/5.jpg', 
    },
    {
        id: 14,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/5.jpg', 
    },
    {
        id: 15,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/5.jpg', 
    },
    {
        id: 16,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/5.jpg', 
    },
    {
        id: 17,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/5.jpg', 
    },
    {
        id: 18,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/5.jpg', 
    },
    {
        id: 19,
        title: 'Sgt. Pepper\'s Lonely Hearts Club Band',
        artist: 'The Beatles',
        year: 1967,
        style: 'Rock',
        country: 'UK',
        image: './img/6.jpg', 
    },
];